language: sh

sudo: required

branches:
  only:
    - master
    - devel

services:
  - docker
    
before_install:
  - docker pull cmbant/cosmobox

install:
  - git clone --depth=1 https://github.com/cmbant/forutils.git forutils
      
script:
  - docker run -v $(pwd):/camb -t cmbant/cosmobox -e TRAVIS_BRANCH /bin/bash -c "/camb/tests/run_tests.sh"

